name: Approval Demo Pipeline

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-om: ubuntu-latest
    steps:
      - name: Print Build
        run: echo "Build completed successfully"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment: production

    steps:
      - name: Deploy Step
        run: echo "Deploying to production..."
